server:
  port: 8083
spring:
  application:
    name: ms-cliente-service



  datasource:
    url: jdbc:h2:mem:ms-cliente
    driver-class-name: org.h2.Driver
    username: sb
    password: password1
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console